profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
    properties.hibernate:
      globally_quoted_identifiers: true
      dialect: org.hibernate.dialect.MySQLDialect
      enable_lazy_load_no_trans: true
      jdbc:
        batch_size: 1000
        time_zone: Asia/Seoul

  datasource:
    hikari:
      max-lifetime: 100000
      maximum-pool-size: 10
    yosep-read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/yosep?useUnicode=true&characterEncoding=utf8&autoreconnect=true
      username: root
      password: fcsdb1!
    yosep-write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/yosep?useUnicode=true&characterEncoding=utf8&autoreconnect=true
      username: root
      password: fcsdb1!

#  sql:
#    init:
#      mode: embedded
#      schema-locations: classpath*:sql/h2-table-create.sql
#      data-locations: classpath*:sql/h2-dat  a-insert.sql