profile: test

application.name: yosep-mvc-boiler-plate-java

server:
  port: 10000
  logging:
    access: true
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      enable_lazy_load_no_trans: true
      jdbc:
        batch_size: 1000
        time_zone: Asia/Seoul
    properties:
      hibernate:
        hibernate:
          show_sql: false

  datasource:
    hikari:
      max-lifetime: 100000
      maximum-pool-size: 10
    yosep-read:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:yosep;Mode=MySQL;DATABASE_TO_LOWER=TRUE
      username: SA
      password:
    yosep-write:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:yosep;MODE=MySQL;DATABASE_TO_LOWER=TRUE
      username: SA
      password:

#  sql:
#    init:
#      mode: embedded
#      schema-locations: classpath*:sql/product-create.sql
#      data-locations: classpath*:sql/h2-data-insert.sql